### ISSUE TITLE
The ECD fails to decompile files from external jar

### ISSUE THREAD

**Issue by jaydeepmehta15** [ecd-plugin/ecd#105]
Hello,

I have added the external jar (custom project without source) to the project build path in eclipse. 

Now, I am trying to open/decompile class file from that jar it is not working & throwing exception as shared below. The de-compilation of class files from maven dependencies works fine.

org.eclipse.core.runtime.CoreException: The Class File Viewer cannot handle the given input ('org.eclipse.jdt.internal.ui.javaeditor.JarEntryEditorInput').
	at org.eclipse.jdt.internal.ui.javaeditor.ClassFileEditor.doSetInputCached(ClassFileEditor.java:672)
	at org.eclipse.jdt.internal.ui.javaeditor.ClassFileEditor.lambda$1(ClassFileEditor.java:663)
	at org.eclipse.jdt.core.JavaCore.lambda$0(JavaCore.java:6142)
	at org.eclipse.jdt.internal.core.JavaModelManager.callReadOnly(JavaModelManager.java:5824)
	at org.eclipse.jdt.core.JavaCore.callReadOnly(JavaCore.java:6126)
	at org.eclipse.jdt.core.JavaCore.runReadOnly(JavaCore.java:6141)
	at org.eclipse.jdt.internal.ui.javaeditor.ClassFileEditor.doSetInput(ClassFileEditor.java:663)
	at org.sf.feeling.decompiler.editor.JavaDecompilerClassFileEditor.doSetInput(JavaDecompilerClassFileEditor.java:430)
	at org.eclipse.ui.texteditor.AbstractTextEditor.lambda$1(AbstractTextEditor.java:3171)

**Eclipse Env**

eclipse.buildId=4.31.0.20240307-1200
java.version=22
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

**Comment by jpstotz** [comment]
I assume you are using the latest ECD version 3.5.0?

Decompilation of class files that belong to a Maven dependencies is usually not performed by ECD as most Maven dependencies also have source code JAR file uploaded to Maven repo. Therefore if you see developer comments (e.g. for classes or methods) in source code ECD was not involved.

 The stack trace you have posted also indicates that ECD was not used at all (no class of ECD included in stack trace). Also ECD does not make use of "Class File Viewer".

If you want to make sure ECD is used for decompilation please open the context menu of the class and select "Open Class With" => and select one of the available decompilers.
